### ISSUE TITLE
could not find function "stripeFormOutput"

### ISSUE THREAD

**Issue by ejazmusavi** [MarkEdmondson1234/stripeR#11]
Please help me to resolve this.
I am using Shiny sample. this error occurs when i run the application.
Warning: Error in stripeFormOutput: could not find function "stripeFormOutput"
  61: dots_list
  60: tags$form
  57: sidebarPanel

**Comment by MarkEdmondson1234** [comment]
I can’t help unless you have an example.


________________________________

**Comment by ejazmusavi** [comment]
Thank you for your response.
here is the ui.R file content

library(shiny)
library(stripeR)

fluidPage(

  # Application title
  titlePanel("StripeR Demo"),

  # Sidebar with a slider input for the number of bins
  sidebarLayout(
    sidebarPanel(
      stripeFormOutput("stripeForm")
    ),

    # Show a plot of the generated distribution
    mainPanel(
      plotOutput("distPlot")
    )
  )
)

and server.R


library(shiny)
library(stripeR)

function(input, output, session){

  status <- stripeShinyInit()

  output$stripeForm <- renderStripeForm(status,
                                        amount="GBP20.00",
                                        plan="Agency - GBP20.00 per month")

  observeStripeCharge(status,
                      input,
                      amount = 2000,
                      currency = "gbp",
                      plan="agency")

}

and put the secret keys in the environment file in the root.

the error is
Warning: Error in stripeFormOutput: could not find function
"stripeFormOutput"
61: dots_list
60: tags$form
57: sidebarPanel

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MarkEdmondson1234** [comment]
The documents needed updating, the correct way is via below:


```r

## server.R
library(shiny)
library(stripeR)

function(input, output, session){

  callModule(stripeRShiny, "stripe1",
             amount=2000,
             plan="example",
             formAmount=reactive("$20.00"),
             formText=reactive("Please pay $20.00"))

}
```

```r
## ui.R
library(shiny)
library(stripeR)

fluidPage(

  titlePanel("StripeR Demo"),

  # A Stripe Form
  sidebarLayout(
    sidebarPanel(
      stripeRShinyUI("stripe1")
    ),

    mainPanel(
      
    )
  )
)

```
