### ISSUE TITLE
Integration with stripe customer portal

### ISSUE THREAD

**Issue by EnzleDev** [MarkEdmondson1234/stripeR#14]
Hi! I was wondering if there was any thought about integrating stripe portal as well? The documentation seems pretty straightforward, I was just not having any luck getting it to launch a new session via js

**Comment by MarkEdmondson1234** [comment]
It's a good idea but I'm not updating this library any more so someone else would need to take it on.

**Comment by EnzleAnalytics** [comment]
No worries, i

**Comment by EnzleDev** [comment]
No worries, just wondering. I’ll keep you abreast of if I can hammer out the customer portal launch as I’m actively working on it now

**Comment by stevepowell99** [comment]
> No worries, just wondering. I’ll keep you abreast of if I can hammer out the customer portal launch as I’m actively working on it now

did you make any progress with this @EnzleAnalytics ?
